receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp:
    endpoint: "collector-gateway:4320"
    tls:
      insecure: true
  logging:
    loglevel: info


processors:
  batch:
    timeout: 1s
  resource:
    attributes:
      - key: component.name1
        value: "agent"
        action: insert

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [logging, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp]